<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <CodeAnalysisVersion>5.0.0</CodeAnalysisVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docfx.App" Version="2.78.5" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="$(CodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(CodeAnalysisVersion)" />
  </ItemGroup>

  <ItemGroup> <!-- Temporary override for a transitive vulnerability. -->
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

</Project>
